### PR TITLE
Initial pull

### PR DESCRIPTION
**Pull request by itsmontoya**

### CODE REVIEW

**Review by OneOfOne — COMMENTED** [review]
Great fucking job man, that's awesome.

One nitpick, the generated files probably (maybe?) shouldn't be included.

**Comment by itsmontoya** [comment]
@OneOfOne are you referring to the js files within the testing dir? I was a little torn about that as well, I figured it would be the path of least resistance if someone wanted to test locally.

**Review by OneOfOne — APPROVED** [review]

**Review by shahzilabid — APPROVED** [review]
That was one of the cleanest PRs I've seen in a while. Really well done dude

**Comment by itsmontoya** [comment]
Thanks @OneOfOne  and @shahzilabid! :) :100:

**Pull request merged**
